blog/urls.py
from django.urls import path
from .views import (
	ArticlesList,
	ArticleDetail,
	CategoryList,
	AuthorList,
	ArticlesPreview,
	SearchList,
)

app_name="blog"
urlpatterns = [
	path('', ArticlesList.as_view(), name="index"),
	path('page/<int:page>', ArticlesList.as_view(), name="index"),
	path('detail/<slug:slug>', ArticleDetail.as_view(), name="detail"),
	path('preview/<int:pk>/', ArticlesPreview.as_view(), name="preview"),
	path('category/<slug:slug>', CategoryList.as_view(), name="category"),
	path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="category"),
	path('author/<slug:username>', AuthorList.as_view(), name="author"),
	path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author"),
	path('search/', SearchList.as_view(), name="search"),
	path('search/page/<int:page>', SearchList.as_view(), name="search")
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from account.views import Login, Register, activate

urlpatterns = [
    path('admin/', admin.site.urls),
    path('comment/', include('comment.urls')),
    path('', include("blog.urls")),
    path('account/', include('account.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from account.models import User
from django.utils.html import format_html
from django.utils import timezone
from extension.utils import jalali_convertor
from django.urls import reverse

# for comment app
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment

# Create your models here.
class ArticleManager(models.Manager):

	def published(self):
		return self.filter(status="p")

class CategoryManager(models.Manager):

	def published(self):
		return self.filter(status=True)



class IPaddress(models.Model):
	ip = models.GenericIPAddressField(verbose_name="آدرس آی پی")

	class Meta:
		verbose_name = "آدرس آی پی"
		verbose_name_plural = "آدرس های آی پی"

class Category(models.Model):
	parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL,  related_name="children", verbose_name="زیردسته")
	title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
	slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس دسته بندی")
	status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
	position = models.IntegerField(verbose_name="جایگاه")
	class Meta:
		verbose_name = "دسته بندی"
		verbose_name_plural = "دسته بندی ها"
		ordering = ['parent__id', 'position']

	def __str__(self):
		return self.title


	objects = CategoryManager()



class Article(models.Model):
	STATUS_CHOICES = (
			('d', 'پیش نویش'),		 #draft
			('p', 'منتشر شده'),		 #publish	
			('i', 'در حال بررسی'), 	 #investigation
			('b', 'برگشت داده شده'), #back
		)

	author = models.ForeignKey(User, null=True,on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
	title = models.CharField(max_length=200, verbose_name="عنوان مقاله")
	slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس مقاله")
	category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
	description = models.TextField(verbose_name="محتوا")
	thumbnail = models.ImageField(upload_to="images", verbose_name="تصویر")
	publish = models.DateTimeField(default=timezone.now, verbose_name="زمان انتشار")
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now= True)
	is_special = models.BooleanField(default=False, verbose_name="عضویت ویژه")
	status = models.CharField(max_length=1, choices=STATUS_CHOICES, verbose_name="وضعیت")
	comments = GenericRelation(Comment, )
	hits = models.ManyToManyField(IPaddress, blank=True, through="ArticleHits", related_name="hits", verbose_name="بازدید ها")

	class Meta:
		verbose_name = "مقاله"
		verbose_name_plural = "مقاله ها"
		ordering = ["-publish"]

	def __str__(self):
		return self.title

	def jpublish(self):
		return jalali_convertor(self.publish)

	jpublish.short_description = "زمان انتشار"

	def category_to_str(self):
		return ", ".join([category.title for category in self.category.published()])


	category_to_str.short_description = "دسته بندی ها"


	def thumbnail_tag(self):
		return format_html("<img width=100 height=75 style='border-radius: 10px' src='{}' />".format(self.thumbnail.url))

	thumbnail_tag.short_description = "نمایه"


	def get_absolute_url(self):
		return reverse("account:home")

	objects = ArticleManager()

class ArticleHits(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	ip_address = models.ForeignKey(IPaddress, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)
		

blog/views.py
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse, JsonResponse
from .models import Article, Category
from account.models import User
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from account.mixins import AuthorAccessMixin
from django.db.models import Count, Q
from datetime import datetime, timedelta
from django.db.models import Q
# Create your views here.

# def index(request, page=1):
# 	articles_list = Article.objects.published()
# 	pagiator = Paginator(articles_list, 1)
# 	articles = pagiator.get_page(page)
# 	context = {
# 		"articles": articles,
# 	}

# 	return render(request, 'blog/home.html', context)


class ArticlesList(ListView):
	# model = Article
	queryset = Article.objects.published()
	paginate_by = 2

# def detail(request, slug):
# 	context = {
# 		"art": get_object_or_404(Article.objects.published(), slug=slug)
# 	}
# 	return render(request, 'blog/detail.html', context)

class ArticleDetail(DetailView):
	
	def get_object(self):
		slug = self.kwargs.get('slug')
		article = get_object_or_404(Article.objects.published(), slug=slug)

		ip_address = self.request.user.ip_address

		if ip_address not in article.hits.all():
			article.hits.add(ip_address)

		return article



class ArticlesPreview(AuthorAccessMixin, DetailView):
	
	def get_object(self):
		pk = self.kwargs.get('pk')
		return get_object_or_404(Article, pk=pk)


# def category(request, slug, page=1):
# 	category = get_object_or_404(Category, slug=slug, status=True)
# 	articles_list = category.articles.published()
# 	pagiator = Paginator(articles_list, 1)
# 	articles = pagiator.get_page(page)
# 	context = {
# 		"articles": articles,
# 		"category": category
# 	}

# 	return render(request, 'blog/category.html', context)


class CategoryList(ListView):
	paginate_by = 1
	template_name = "blog/category_list.html"

	def get_queryset(self):
		global category
		slug = self.kwargs.get('slug')
		category = get_object_or_404(Category.objects.published(), slug=slug,)
		return category.articles.published()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['category'] = category
		return context

class AuthorList(ListView):
	paginate_by = 1
	template_name = "blog/author_list.html"

	def get_queryset(self):
		global author
		username = self.kwargs.get('username')
		author = get_object_or_404(User, username=username)
		return author.articles.published()

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['author'] = author
		return context


class SearchList(ListView):
	paginate_by = 1
	template_name = "blog/search_list.html"

	def get_queryset(self):
		search = self.request.GET.get('q')
		return Article.objects.filter(Q(description__icontains=search) | Q(description__icontains=search))

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['search'] = self.request.GET.get('q')
		return context

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="index.html">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="index.html">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="about.html">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="post.html">Sample Post</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="contact.html">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('assets/img/about-bg.jpg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comment_tags %}


{% block custome-header %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/rtl.css' %}">
{% endblock %}

{% block title %}
    {{ object.title }}
{% endblock %}



{% block main %}
<header class="masthead" style="background-image: url('{{object.thumbnail.url}}')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                            <h1>{{ object.title }}
                                {% if article.is_special %}
                                <span class="badge bg-danger" style="font-size: 14px;">ویژه</span>
                                {% endif %}
                            </h1>
                            <span class="subheading">{{ object.jpublish }}</span>
                            <div>بازدید ها: {{ object.hits.count }}</div>
                    </div>
                </div>
            </div>
        </div>
</header>


<article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7" style="text-align: justify;">
                        {% if object.is_special %}
                            {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
                                {{ object.description|safe }}
                            {% else %}
                                {{article.description|striptags|truncatewords:30}}
                                <p class="alert alert-warning">این مقاله ویژه است و برای مشاهده آن باید <a class="alert-link" href="#">اشتراک ویژه</a> داشته باشید</p>
                            {% endif %}
                        {% else %}
                            {{ object.description|safe }}
                        {% endif %}

                        
                        {% render_comments object request %}
                        {% include_bootstrap %}
                    </div>
                </div>
            </div>
</article>
{% endblock %}

templates/blog/article_list.html
{% extends 'blog/list.html' %}

{% block header %}{% endblock %}

{% block previous_page_url %}
  {% url 'blog:index' page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
  {% url 'blog:index' page_obj.next_page_number %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">نویسنده: {{ author.get_full_name }}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}

templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>سیلسیم{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/styles.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

  {% block custome-header %}

  {% endblock %}

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">{% title %}</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      {% category_navbar %}
    </div>
  </nav>

  {% block main %}

  {% endblock %}

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/category_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">دسته‌بندی: {{category.title}}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:category' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:category' category.slug page_obj.next_page_number %}
{% endblock %}

templates/blog/list.html
{% extends 'blog/base.html' %}

{% load static %}
{% load base_tags %}
{% load humanize %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>سیلسیم</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        {% block header %}{% endblock %}
        {% popular_articles %}
        {% hot_articles %}
        

        {% for article in object_list %}
          <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{article.title}} 
              {% if article.is_special %}
                  <span class="badge bg-danger" style="font-size: 14px;">ویژه</span>
              {% endif %}
              </h2>
              <h3 class="post-subtitle">
                {{article.description|striptags|truncatewords:30}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط:
              <a href="{% url 'blog:author' article.author.username %}">{{ article.author.get_full_name }}</a>
              {{article.publish|naturaltime}}</p>
            <div>
              {% for cat in article.category.active %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
              {% endfor %}
              <div>بازدید ها: {{ article.hits.count }}</div>
            </div>
          </div>
          <hr>
        {% empty %}
          <p>متاسفانه محتوایی  برای نمایش وجود ندارد</p>
        {% endfor %}
        <!-- Pager -->
        {% if is_paginated %}
          <div class="clearfix pager-botton">
            {% if page_obj.has_previous %}
              <a class="btn btn-primary float-right ml-3" href="{% block previous_page_url %}{% endblock %}">پست های جدید &rarr;</a>
            {% endif %}
            {% if page_obj.has_next %}
              <a class="btn btn-primary float-right" href="{% block next_page_url %}{% endblock %}">پست های قدیمی &larr;</a>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

templates/blog/search_list.html
{% extends 'blog/list.html' %}

{% block header %}
    <h3 class="alert alert-primary text-center">جستوجو: {{ search }}</h3>
{% endblock %}

{% block previous_page_url %}
    {% url 'blog:search' page_obj.previous_page_number %}?q={{search}}
{% endblock %}

{% block next_page_url %}
    {% url 'blog:search' page_obj.next_page_number %}?q={{search}}
{% endblock %}